apiVersion: v1
kind: Service
metadata:
  name: boot-example-docker-service
spec:
  type: NodePort
  selector:
    app: boot-example-docker
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080